apiVersion: kubevious.io/v1alpha1
kind: Library
metadata:
  name: library
spec:
  rules:
  - name: argo-rollout-analysis-template-ref
    path: argo-rollout/rollout-analysis-template-ref.yaml
    location: argo-rollout
    summary: Validate Argo Rollout to Analysis Template reference.
    categories:
    - argo
    - rollout
    - analysis
    - reference
  - name: certificate-to-issuer-ref
    path: cert-manager/certificate-to-issuer-ref.yaml
    location: cert-manager
    summary: Validate CertManager Certificate to Issuer reference.
    categories:
    - cert-manager
    - certificate
    - issuer
    - reference
  - name: container-env-config-map-ref
    path: k8s/container/env-config-map-ref.yaml
    location: k8s/container
    summary: Validate ContainerSpec environment variable ConfigMap reference.
    categories:
    - k8s
    - container
    - environment-variable
    - config-map
    - reference
  - name: container-env-from-config-map-ref
    path: k8s/container/env-from-config-map-ref.yaml
    location: k8s/container
    summary: Validate ContainerSpec envFrom variables projection ConfigMap reference.
    categories:
    - k8s
    - container
    - environment-variable
    - config-map
    - reference
  - name: container-env-from-secret-ref
    path: k8s/container/env-from-secret-ref.yaml
    location: k8s/container
    summary: Validate ContainerSpec envFrom variables projection Secret reference.
    categories:
    - k8s
    - container
    - environment-variable
    - secret
    - reference
  - name: container-env-secret-ref
    path: k8s/container/env-secret-ref.yaml
    location: k8s/container
    summary: Validate ContainerSpec environment variable Secret reference.
    categories:
    - k8s
    - container
    - environment-variable
    - secret
    - reference
  - name: container-latest-image
    path: k8s/container/latest-image.yaml
    location: k8s/container
    summary: Validate ContainerSpec image to have non latest tag.
    categories:
    - k8s
    - container
    - image
    - latest
  - name: container-volume-mount-ref
    path: k8s/container/volume-mount-ref.yaml
    location: k8s/container
    summary: Validate ContainerSpec volume mount to PodSpec volume reference.
    categories:
    - k8s
    - container
    - volume
    - volume-mount
    - reference
  - name: gateway-certificate-secret-ref
    path: k8s/gateway-api/gateway/certificate-ref.yaml
    location: k8s/gateway-api/gateway
    summary: Validate Gateway to Certificate Secret reference.
    categories:
    - k8s
    - gateway-api
    - gateway
    - certificate
    - reference
  - name: gateway-class-ref
    path: k8s/gateway-api/gateway/gateway-class-ref.yaml
    location: k8s/gateway-api/gateway
    summary: Validate Gateway to GatewayClass reference.
    categories:
    - k8s
    - gateway-api
    - gateway
    - gateway-class
    - reference
  - name: gateway-unique-listeners
    path: k8s/gateway-api/gateway/unique-listeners.yaml
    location: k8s/gateway-api/gateway
    summary: Validate Gateway to have unique listeners.
    categories:
    - k8s
    - gateway-api
    - gateway
    - unique-listeners
  - name: hpa-scale-target-ref
    path: k8s/hpa/hpa-scale-target-ref.yaml
    location: k8s/hpa
    summary: Validate HorizontalPodAutoscaler to scale target reference.
    categories:
    - k8s
    - hpa
    - target
    - reference
  - name: http-route-backend-ref
    path: k8s/gateway-api/http-route/backend-ref.yaml
    location: k8s/gateway-api/http-route
    summary: Validate HTTPRoute to Backend reference.
    categories:
    - k8s
    - gateway-api
    - http-route
    - backend
    - reference
  - name: http-route-gateway-ref
    path: k8s/gateway-api/http-route/gateway-ref.yaml
    location: k8s/gateway-api/http-route
    summary: Validate HTTPRoute to Gateway reference.
    categories:
    - k8s
    - gateway-api
    - http-route
    - gateway
    - reference
  - name: ingress-ext-service-ref
    path: k8s/ingress/ingress-ext-service-ref.yaml
    location: k8s/ingress
    summary: Validate Ingress (extension) to Service reference.
    categories:
    - k8s
    - ingress
    - ingress-extension
    - service
    - reference
  - name: ingress-service-ref
    path: k8s/ingress/ingress-service-ref.yaml
    location: k8s/ingress
    summary: Validate Ingress to Service reference.
    categories:
    - k8s
    - ingress
    - service
    - reference
  - name: ingress-tls-rule-domain-match
    path: k8s/ingress/ingress-tls-rule-domain-match.yaml
    location: k8s/ingress
    summary: Validate Ingress TLS and rule domain match.
    categories:
    - k8s
    - ingress
    - ingress-extension
    - tls
    - domain
  - name: ingress-to-cert-issuer-ref
    path: cert-manager/ingress-to-cert-issuer-ref.yaml
    location: cert-manager
    summary: Validate Ingress to CertManager Issuer reference.
    categories:
    - cert-manager
    - ingress
    - issuer
    - reference
  - name: ingress-unique-route-rules
    path: k8s/ingress/ingress-unique-route-rules.yaml
    location: k8s/ingress
    summary: Validate Ingresses to have unique routing rules.
    categories:
    - k8s
    - ingress
    - ingress-extension
    - unique-route
  - name: istio-virtual-service-to-gateway-ref
    path: istio/virtual-service-to-gateway-ref.yaml
    location: istio
    summary: Validate Istio VirtualService to IstioGateway reference.
    categories:
    - istio
    - virtual-service
    - istio-gateway
    - reference
  - name: kong-consumer-to-credential-secret-ref
    path: kong/consumer-to-credential-secret-ref.yaml
    location: kong
    summary: Validate KongConsumer to Credential Secret reference.
    categories:
    - kong
    - consumer
    - credential
    - secret
    - reference
  - name: kong-plugin-ref
    path: kong/plugin-ref.yaml
    location: kong
    summary: Validate Ingress and Service to Kong Plugin reference
    categories:
    - kong
    - ingress
    - service
    - plugin
    - reference
  - name: multiple-default-ingress-classes
    path: k8s/ingress/multiple-default-ingress-classes.yaml
    location: k8s/ingress
    summary: Validate IngressClasses to have at most only one default.
    categories:
    - k8s
    - ingress-class
    - unique-default
  - name: network-policy-pod-selector-ref
    path: k8s/network-policy/network-policy-pod-selector-ref.yaml
    location: k8s/network-policy
    summary: Validate NetworkPolicy to PodSpec reference.
    categories:
    - k8s
    - network-policy
    - pod-spec
    - reference
  - name: pod-spec-service-account-ref
    path: k8s/pod-spec/service-account-ref.yaml
    location: k8s/pod-spec
    summary: Validate PodSpec to ServiceAccount reference.
    categories:
    - k8s
    - pod-spec
    - service-account
    - reference
  - name: pod-spec-volume-config-map-ref
    path: k8s/pod-spec/volume-config-map-ref.yaml
    location: k8s/pod-spec
    summary: Validate PodSpec volume mount ConfigMap reference.
    categories:
    - k8s
    - pod-spec
    - config-map
    - volume
    - reference
  - name: pod-spec-volume-pvc-ref
    path: k8s/pod-spec/volume-pvc-ref.yaml
    location: k8s/pod-spec
    summary: Validate PodSpec volume mount PersistentVolumeClaim reference.
    categories:
    - k8s
    - pod-spec
    - pvc
    - volume
    - reference
  - name: pod-spec-volume-secret-ref
    path: k8s/pod-spec/volume-secret-ref.yaml
    location: k8s/pod-spec
    summary: Validate PodSpec volume mount Secret reference.
    categories:
    - k8s
    - pod-spec
    - secret
    - volume
    - reference
  - name: replica-count-check
    path: k8s/workload/replica-count-check.yaml
    location: k8s/workload
    summary: Checks Deployments to have min/max replicas - with or without HPAs.
    categories:
    - k8s
    - deployment
    - replica-count
  - name: role-binding-role-ref
    path: k8s/rbac/role-binding-role-ref.yaml
    location: k8s/rbac
    summary: Validate RoleBinding and ClusterRoleBinding to Role and ClusterRole
      reference.
    categories:
    - k8s
    - rbac
    - binding
    - role
    - reference
  - name: role-binding-service-account-ref
    path: k8s/rbac/role-binding-service-account-ref.yaml
    location: k8s/rbac
    summary: Validate RoleBinding and ClusterRoleBinding to ServiceAccount subject
      reference.
    categories:
    - k8s
    - rbac
    - binding
    - service-account
    - reference
  - name: service-selector-ref
    path: k8s/service/service-selector-ref.yaml
    location: k8s/service
    summary: Validate Service to PodSpec label selector reference.
    categories:
    - k8s
    - service
    - pod-spec
    - reference
