apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: pod-spec-volume-pvc-ref
spec:
  summary: |
    Validate PodSpec volume mount PersistentVolumeClaim reference.
  target: |
    Shortcut("PodSpec")
  categories:
    - k8s
    - pod-spec
    - pvc
    - volume
    - reference
  rule: |
    for(const volume of config.spec?.volumes ?? [])
    {
      if (volume.persistentVolumeClaim)
      {
        checkPvcRef(volume.name, volume.persistentVolumeClaim);
      }
    }

    function checkPvcRef(volumeName, pvcRef)
    {
      const pvcItem = ApiVersion('v1')
                        .Kind("PersistentVolumeClaim")
                        .name(pvcRef.claimName)
                        .single()
      if (!pvcItem)
      {
        error(`Could not find PersistentVolumeClaim ${pvcRef.claimName} referenced in volume ${volumeName}.`);
      }
    }