apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: gateway-unique-listeners
spec:
  summary: |
    Validate Gateway to have unique listeners.
  target: |
    Api('gateway.networking.k8s.io')
      .Kind('Gateway')
  categories:
    - k8s
    - gateway-api
    - gateway
    - unique-listeners    
  rule: |
    const duplicates = helpers.findDuplicates(config.spec?.listeners, x => x.name);
    if (duplicates.length > 0)
    {
      error(`Duplicate listeners found: [${duplicates.join(', ')}]`);
    }
    