apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: istio-virtual-service-to-gateway-ref
spec:
  summary: |
    Validate Istio VirtualService to IstioGateway reference.
  categories:
    - istio
    - virtual-service
    - istio-gateway
    - reference 
  target: |
    Api('networking.istio.io')
      .Kind('VirtualService')
  rule: |
    for(let gatewayTarget of (config.spec?.gateways || []))
    {
      if (gatewayTarget === 'mesh')
      {
        continue;
      }

      let gatewayNaming = gatewayTarget.split('/');
      if (gatewayNaming.length == 2) {
        let gatewayItem = 
            Api('networking.istio.io')
                .Kind('Gateway')
                .name(gatewayNaming[1])
                .namespace(gatewayNaming[0])
                .single();
          
        if (!gatewayItem)
        {
          error(`Did not find Gateway ${gatewayNaming[1]} in namespace ${gatewayNaming[0]}`); 
        }
      } 
      else if (gatewayNaming.length == 1)
      {
        let gatewayItem =
            Api('networking.istio.io')
                  .Kind('Gateway')
                  .name(gatewayNaming[0])
                  .single();
            
        if (!gatewayItem)
        {
          error(`Did not find Gateway ${gatewayNaming[0]}`); 
        }
      }
      else
      {
        error(`Invalid gateway name: ${gatewayTarget}`); 
      }
    }