apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: gcp-config-connector-sql-user-to-instance-ref
spec:
  summary: |
    Validate GCP Config Connector SQL User to Instance reference.
  categories:
    - gcp-config-connector
    - sql-user
    - sql-instance
    - reference 
  target: |
    Api('sql.cnrm.cloud.google.com')
      .Kind('SQLUser')
  rule: |
    let sqlInstanceName = config.spec?.instanceRef?.name
    if (sqlInstanceName)
    {
      let sqlInstanceItem = 
          Api('sql.cnrm.cloud.google.com')
              .Kind('SQLInstance')
              .name(sqlInstanceName)
              .single();
      if (!sqlInstanceItem)
      {
        error(`Did not find SQLInstance ${sqlInstanceName}`);
      }              
    }
  