apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: gcp-config-connector-sql-user-to-password-secret-ref
spec:
  summary: |
    Validate GCP Config Connector SQL User to Password Secret reference.
  categories:
    - gcp-config-connector
    - sql-user
    - secret
    - reference 
  target: |
    Api('sql.cnrm.cloud.google.com')
      .Kind('SQLUser')
  rule: |
    let secretKeyRef = config.spec?.password?.valueFrom?.secretKeyRef
    if (secretKeyRef)
    {
      const secretItem = Shortcut("Secret", secretKeyRef.name)
                            .single();
      if (!secretItem)
      {
        error(`Could not find Secret ${secretKeyRef.name}`);
      }
      else
      {
        const dataObj = secretItem.config.data ?? {};
        if (dataObj[secretKeyRef.key] === undefined)
        {
          const stringDataObj = secretItem.config.stringData ?? {};
          if (stringDataObj[secretKeyRef.key] === undefined)
          {
            error(`Could not find data key ${secretKeyRef.key} in Secret ${secretKeyRef.name}`);
          }
        }
      }
    }
  