apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: kong-consumer-to-credential-secret-ref
spec:
  summary: |
    Validate KongConsumer to Credential Secret reference.
  categories:
    - kong
    - consumer
    - credential
    - secret
    - reference
  target: |
    Api("configuration.konghq.com")
      .Kind("KongConsumer")
  rule: |
    for(const secretName of config.credentials ?? [])
    {
      const secret = Shortcut("Secret", secretName)
        .single();

      if (!secret)
      {
        error(`Could not find Secret ${secretName} referenced in credentials`);
      }
    }