apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: http-route-gateway-ref
spec:
  summary: |
    Validate HTTPRoute to Gateway reference.
  target: |
    Api('gateway.networking.k8s.io')
      .Kind('HTTPRoute')
  categories:
    - k8s
    - gateway-api
    - http-route
    - gateway
    - reference
  rule: |
    for(const gatewayRef of config.spec?.parentRefs ?? [])
    {
      const gatewayItem = Api('gateway.networking.k8s.io')
                            .Kind('Gateway')
                            .name(gatewayRef.name)
                            .namespace(gatewayRef.namespace)
                            .single();
      if (!gatewayItem)
      {
        if (gatewayRef.namespace) {
          error(`Gateway ${gatewayRef.name} not found in namespace ${gatewayRef.namespace}`);
        } else {
          error(`Gateway ${gatewayRef.name} not found`);
        }
      }
      else
      {
        if (gatewayRef.sectionName) {
          const listener = _.find(gatewayItem.config?.spec.listeners, x => x.name === gatewayRef.sectionName);
          if (!listener) {
              error(`Could not find listener ${gatewayRef.sectionName} in Gateway ${gatewayRef.name}`);
          }
        }
      }
    }