apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: role-binding-service-account-ref
spec:
  summary: |
    Validate RoleBinding and ClusterRoleBinding to ServiceAccount subject reference.
  categories:
    - k8s
    - rbac
    - binding
    - service-account
    - reference
  target: |
    Union(
      Api('rbac.authorization.k8s.io')
        .Kind("ClusterRoleBinding")
        .isClusterScope(true),
      Api('rbac.authorization.k8s.io')
        .Kind("RoleBinding"),
    )
  rule: |
    for(const subject of config.subjects ?? [])
    {
      if (subject.kind === 'ServiceAccount')
      {
        const serviceAccount = ApiVersion('v1')
                                .Kind('ServiceAccount')
                                .name(subject.name)
                                .namespace(subject.namespace ?? item.namespace)
                                .single();

        if (!serviceAccount)
        {
          if (subject.name !== "default")
          {
            error(`Could not find ServiceAccount ${subject.name}`);
          }
        }
      }
    }