apiVersion: kubevious.io/v1alpha1
kind: ClusterRule
metadata:
  name: certificate-to-issuer-ref
spec:
  summary: |
    Validate CertManager Certificate to Issuer reference.
  target: |
    Api('cert-manager.io')
      .Kind('Certificate')
  rule: |
    const issuerRef = config.spec?.issuerRef;
    if (!issuerRef) {
      error('issuerRef is not set');
      return;
    }

    const issuerRefKind = issuerRef.kind ?? 'Issuer';

    const issuerRefName = config.spec?.issuerRef?.name;
    if (!issuerRefName) {
      error('issuerRef.name is not set.');
      return;
    }

    const issuer = ApiVersion('cert-manager.io/v1')
                    .Kind(issuerRefKind)
                    .name(issuerRefName)
                    .isClusterScope(issuerRefKind.startsWith('Cluster'))
                    .single();
    if (!issuer) {
      error(`Could not find the Certificate ${issuerRefKind} ${issuerRefName}`);
    }